<a href="https://colab.research.google.com/github/gimhanul/dataAnalysis/blob/master/team.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import random
import pandas as pd

lt = []


for i in range(5):
  lt.append(list(range(1, 17)))
for i in range(1, 5):
  random.shuffle(lt[i])


df = pd.DataFrame(lt)
df = df.T #열과 행 전환
df.columns = ['조', '1반', '2반', '3반', '4반']
df = df.set_index('조') #조를 index로 설정


#예외 처리
df.loc[df[df['1반'] == 16].index, '1반'] = '없음'
df.loc[df[df['2반'] == 8].index, '2반'] = '8번, 빠질 수 있음.'
df.loc[df[df['4반'] == 8].index, '4반'] = '없음'
df.loc[df[df['4반'] == 9].index, '4반'] = 17
df

    1반            2반  3반  4반
조
1   14             2   2   2
2   10             9   1   4
3   15            11   7  10
4   11            14   5   1
5    4             4  10  14
6   없음            15  11  17
7    6            12  12   3
8    5            10   6   6
9    3             6  13  없음
10   2            13  15   5
11   9             7   9  16
12  12             3  14   7
13   7             1   3  11
14   1             5  16  12
15   8            16   4  15
16  13  8번, 빠질 수 있음.   8  13